server:
  port: 8899

spring:
  profiles:
    active: prod
  application:
    name: meicloud-paas-preview

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: html5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false

  servlet:
    multipart:
      enabled: true
      max-file-size: -1
      max-request-size: 1024MB

swagger:
  enable: true

logging:
  config: classpath:log4j2.xml