meicloud:
  apaas:
    preview:
      max-file-size: 30
      store-path: /data

jodconverter:
  local:
    enabled: true
    # 设置LibreOffice主目录
    office-home: /usr/lib64/libreoffice
    port-numbers: 8100
    max-tasks-per-process: 20d
    task-execution-timeout: 140000
    task-queue-timeout: 90000
    kill-existing-process: true
    process-timeout: 180000
    process-retry-interval: 1000
    working-dir: /tmp

logging:
  config: classpath:logback.xml
  file:
    path: /apps/logs
  level:
    root: info